# Header
menu:
  首页: /
  存档: /archives
  关于这里: /about
  关于我: /aboutme

# Content
excerpt_link: 阅读全文
fancybox: true

# Sidebar
sidebar: right
widgets:
- recent_posts
- category
- tagcloud
- archive
- links
thumbnail: false

# Contacts
contacts:
  github: https://github.com/wengpingbo
  weibo: http://weibo.com/echowpb
  google-plus: https://plus.google.com/u/0/117917427002657037112
  #twitter: '#'
  #facebook: '#'
  #dribbble: '#'
  rss: /atom.xml

# Links
links:
  TINYLAB: http://tinylab.org
  LZUOSS: http://oss.lzu.edu.cn

# Miscellaneous
google_analytics: UA-62257978-1
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:
