# Header
menu:
  首页: /
  存档: /archives
  关于我: /about

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- recent_posts
- category
- tagcloud
- archive
- links
thumbnail: false

# Contacts
contacts:
  github: https://github.com/wengpingbo
  #twitter: '#'
  #facebook: '#'
  #dribbble: '#'
  rss: /atom.xml

# Links
links:
  TINYLAB: http://tinylab.org
  LZUOSS: http://oss.lzu.edu.cn

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:
